### ISSUE TITLE
Some feedbacks

### ISSUE THREAD

**Issue by Durss** [teddybrine/goxlr-js#1]
Hello !

First of all, thank you for that work!

I have a few feedbacks if I may :)

The IP is hardcoded to 127.0.0.1 which will work for most people, but it would be nice to expose that as a parameter so we can control a remote device as well.
Same for the port in case we'd like to use another port that's then forwared to the GoXLR socket port.
having the possibility to specify both IP and port would open more usage

If I'm not mistaken your creating/closing the connection for every call?
If so, that seems a bit rough. Keeping the connection open and simply reusing it for every new request would be preferable I think.

Having typescript typings would be pretty awesome as well :D

Because of all the above I can't use that lib but I'm sure it will help others !

Best regards :)

**Comment by teddybrine** [comment]
Hiya!

It seems like you have taken the words out of my brain. I’m currently working on having a custom IP and Port and have a test build where the connection isn’t opened and closed on each function being ran. As soon as I have a few hours to myself I’ll continue to work on these features as I know that they are important.

I’ve not personally dealt with Typescript that much, maybe I’ll look into it.

Cheers!

**Comment by Durss** [comment]
That's a fast answer :D

Take your time!
I'm gonna try to make a Typescript port _(while adressing the points above)_, I'll share it with you if you if I that gives anything if want :)
I have no goxlr tho so testing it is gonna be a challenge but I'll annoy a friend or two haha

**Comment by teddybrine** [comment]
I’d also be happy to test it for you, @t3d.uk on discord?

**Comment by Durss** [comment]
If that can be of any interest, I made a super light typescript implementation with a persistent websocket connection.
You can find it here :
https://github.com/Durss/Twitchat/blob/dev/src_front/utils/goxlr/GoXLRSocket.ts

Also typings for the "GetStatus" result can be found here:
https://github.com/Durss/Twitchat/blob/dev/src_front/types/GoXLRTypes.ts

Could be cleaner but things are working fine :)

**Comment by teddybrine** [comment]
Thank you, i’m not quite sure what I could do with this now.
